import os
from botocore.exceptions import ClientError
from src.utils.aws_client import get_aws_client
from src.utils.logger import get_logger

logger = get_logger(__name__)


def send_sns_notification(report_summary: dict, dry_run: bool) -> bool:
    """
    Sends a summary of the cost optimization run to an SNS topic.
    The message contains resource counts, total savings, and links to the S3 reports.
    """
    sns_topic_arn = os.environ.get("SNS_TOPIC_ARN")
    if not sns_topic_arn:
        logger.warning("SNS_TOPIC_ARN environment variable not set. Skipping notifications.")
        return False

    sns_client = get_aws_client('sns')
    
    total_savings = report_summary.get("total_savings", 0.0)
    total_resources = report_summary.get("total_resources", 0)
    s3_html = report_summary.get("s3_html_url", "N/A")
    s3_json = report_summary.get("s3_json_url", "N/A")
    date = report_summary.get("report_date", "Today")
    
    run_mode = "DRY-RUN" if dry_run else "EXECUTION"
    
    subject = f"AWS Cost Optimization Report - {date} ({run_mode})"
    
    message = f"""AWS Cost Optimization Platform Summary - {date}
--------------------------------------------------
Run Mode: {run_mode}
Estimated Monthly Savings: ${total_savings:.2f}
Total Idle Resources Remediated/Previewed: {total_resources}

Full Reports Uploaded to S3:
- HTML Report: {s3_html}
- JSON Report: {s3_json}

Resource Type Detail Breakdown can be reviewed in the reports linked above.
--------------------------------------------------
This email is auto-generated by the AWS Cost Optimization CronJob / Lambda.
"""

    try:
        logger.info(f"Publishing summary message to SNS Topic: {sns_topic_arn}")
        response = sns_client.publish(
            TopicArn=sns_topic_arn,
            Subject=subject,
            Message=message
        )
        logger.info(f"Notification published successfully. Message ID: {response.get('MessageId')}")
        return True
    except ClientError as e:
        logger.error(f"Failed to publish notification to SNS Topic {sns_topic_arn}: {e}")
        return False
